In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, LeakyReLU, Input
from tensorflow.keras.models import Sequential

In [2]:
units = 10
features = 54
inputs = tf.keras.layers.Input(shape=(features,))
h_1 = Dense( units=units, kernel_initializer='he_normal', bias_initializer='zeros')(inputs)
h_2 = BatchNormalization()(h_1)
h_3 = LeakyReLU(alpha=0.01)(h_2)
outputs = Dropout(0.5)(h_3)

model = tf.keras.Model(inputs=[inputs], outputs=[outputs])

In [3]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 54)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                550       
_________________________________________________________________
batch_normalization (BatchNo (None, 10)                40        
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 10)                0         
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
Total params: 590
Trainable params: 570
Non-trainable params: 20
_________________________________________________________________


In [4]:
inputs = tf.random.normal([1, features])
inputs

<tf.Tensor: shape=(1, 54), dtype=float32, numpy=
array([[ 1.4135814 ,  0.6421391 , -0.27953327, -2.043901  ,  1.4690732 ,
        -1.3739818 , -1.3444251 , -1.3715066 , -0.97921956,  1.5884216 ,
         0.2527496 , -1.9697795 ,  0.2984658 , -0.89714307,  0.7142499 ,
        -1.6682302 ,  0.18361786,  0.53128904,  0.41940412,  0.5479198 ,
         1.2807066 , -0.53527325,  1.2284347 ,  1.413726  ,  1.6461408 ,
         2.166583  , -1.8103286 ,  0.9457093 , -0.12526248, -2.1458645 ,
        -0.171338  ,  0.5207195 , -1.5163895 ,  1.5715888 ,  1.4130744 ,
        -0.16182834, -0.16761403, -2.6016126 , -0.7709971 ,  1.5710032 ,
        -0.9679242 , -0.90455556, -1.2925057 , -1.9625329 ,  0.67504823,
         0.7283445 , -0.70282364, -0.8818216 ,  0.75903773, -0.26363954,
        -0.20570222,  0.05438731, -1.0121843 ,  0.33663833]],
      dtype=float32)>

In [5]:
# outputs = model(inputs, training=True)
outputs = model(inputs)
outputs.shape

TensorShape([1, 10])

In [6]:
outputs

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ 0.03434995,  1.2177731 ,  0.6577553 ,  0.6621918 ,  0.8766108 ,
        -0.02241789,  1.2086124 , -0.00200204, -0.01769386, -0.00752769]],
      dtype=float32)>

In [7]:
outputs = model(inputs, training=True)
outputs

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
model.layers

In [13]:
inputs

<tf.Tensor: shape=(1, 54), dtype=float32, numpy=
array([[ 1.4135814 ,  0.6421391 , -0.27953327, -2.043901  ,  1.4690732 ,
        -1.3739818 , -1.3444251 , -1.3715066 , -0.97921956,  1.5884216 ,
         0.2527496 , -1.9697795 ,  0.2984658 , -0.89714307,  0.7142499 ,
        -1.6682302 ,  0.18361786,  0.53128904,  0.41940412,  0.5479198 ,
         1.2807066 , -0.53527325,  1.2284347 ,  1.413726  ,  1.6461408 ,
         2.166583  , -1.8103286 ,  0.9457093 , -0.12526248, -2.1458645 ,
        -0.171338  ,  0.5207195 , -1.5163895 ,  1.5715888 ,  1.4130744 ,
        -0.16182834, -0.16761403, -2.6016126 , -0.7709971 ,  1.5710032 ,
        -0.9679242 , -0.90455556, -1.2925057 , -1.9625329 ,  0.67504823,
         0.7283445 , -0.70282364, -0.8818216 ,  0.75903773, -0.26363954,
        -0.20570222,  0.05438731, -1.0121843 ,  0.33663833]],
      dtype=float32)>

In [26]:
outputs = inputs
for curr_layer in model.layers:
    outputs = curr_layer(outputs, training=True)
    print(curr_layer.name)
    print("\t",outputs)
    print()

input_1
	 tf.Tensor(
[[ 1.4135814   0.6421391  -0.27953327 -2.043901    1.4690732  -1.3739818
  -1.3444251  -1.3715066  -0.97921956  1.5884216   0.2527496  -1.9697795
   0.2984658  -0.89714307  0.7142499  -1.6682302   0.18361786  0.53128904
   0.41940412  0.5479198   1.2807066  -0.53527325  1.2284347   1.413726
   1.6461408   2.166583   -1.8103286   0.9457093  -0.12526248 -2.1458645
  -0.171338    0.5207195  -1.5163895   1.5715888   1.4130744  -0.16182834
  -0.16761403 -2.6016126  -0.7709971   1.5710032  -0.9679242  -0.90455556
  -1.2925057  -1.9625329   0.67504823  0.7283445  -0.70282364 -0.8818216
   0.75903773 -0.26363954 -0.20570222  0.05438731 -1.0121843   0.33663833]], shape=(1, 54), dtype=float32)

dense
	 tf.Tensor(
[[ 0.03436713  1.218382    0.6580842   0.6625229   0.87704915 -2.2429101
   1.2092168  -0.20030391 -1.7702703  -0.75314534]], shape=(1, 10), dtype=float32)

batch_normalization
	 tf.Tensor([[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 10), dtype=float32)

leaky_re_lu